print(5>3)
print(6<4)
print(3==7)
print(2<=8)
print(1>=5)
print(4!=5)
print(4>=2)
print(6<=3)
print(5!=8)
print(8>1)

print(True or False)
print(False or True)
print(False or False)
print(True or True)
print(True and False)
print(False and True)
print(False and False)
print(True and True)
print(True and False and True)
print(False or True or False)